name: Push to Docker

on:
    push:
        branches:
            - main
        paths:
            - go.mod
            - go.sum
            - "**/*.{go,gotmpl}"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: docker/setup-qemu-action@v3
            - uses: docker/setup-buildx-action@v3

            - uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: 🚀 Build & push
              uses: docker/build-push-action@v5
              with:
                  push: true
                  tags: zyrouge/sailing-seas:latest
                  file: Containerfile
